apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: app1-mtls
spec:
  host: {{ .Values.app1.name }}.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: app2-mtls
spec:
  host: {{ .Values.app2.name }}.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL